import numpy as np

class Vector:
    def __init__(self, data: int | list[float] = ...) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, val: float) -> None: ...
    def dot(self, other: Vector) -> float: ...
    def norm(self) -> float: ...
    def normalized(self) -> Vector: ...
    def __add__(self, other: Vector) -> Vector: ...
    def __sub__(self, other: Vector) -> Vector: ...
    def __mul__(self, scalar: float) -> Vector: ...
    def __rmul__(self, scalar: float) -> Vector: ...
    def to_list(self) -> list[float]: ...

class Matrix:
    def __init__(self, rows: int = ..., cols: int = ...) -> None: ...
    def rows(self) -> int: ...
    def cols(self) -> int: ...
    def size(self) -> int: ...
    def __call__(self, i: int, j: int) -> float: ...
    def __getitem__(self, idx: tuple[int, int]) -> float: ...
    def __setitem__(self, idx: tuple[int, int], val: float) -> None: ...
    def __mul__(self, other: Matrix) -> Matrix: ...
    def __add__(self, other: Matrix) -> Matrix: ...
    def __sub__(self, other: Matrix) -> Matrix: ...
    def transpose(self) -> Matrix: ...
    def identity(self, n: int) -> Matrix: ...
    def zeros(self, rows: int, cols: int) -> Matrix: ...
    def random(self, rows: int, cols: int, seed: int = ...) -> Matrix: ...
    def to_list(self) -> list[list[float]]: ...

class KNN:
    def __init__(self, k: int = 3) -> None: ...
    def fit(self, X: np.ndarray, y: list[int]) -> None: ...
    def predict(self, X: np.ndarray) -> list[int]: ...
    @property
    def k(self) -> int: ...

class LinearRegression:
    def __init__(
        self,
        learning_rate: float = 0.01,
        epochs: int = 1000,
        fit_intercept: bool = True,
    ) -> None: ...
    def fit(self, X: np.ndarray, y: list[float]) -> None: ...
    def predict(self, X: np.ndarray) -> list[float]: ...
    def score(self, X: np.ndarray, y: list[float]) -> float: ...
    def compute_cost(self, X: np.ndarray, y: list[float]) -> float: ...
    @property
    def weights(self) -> Vector: ...
    @property
    def bias(self) -> float: ...
    @property
    def learning_rate(self) -> float: ...
    @property
    def epochs(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

class LogisticRegression:
    def __init__(
        self,
        learning_rate: float = 0.01,
        epochs: int = 1000,
        fit_intercept: bool = True,
    ) -> None: ...
    def fit(self, X: np.ndarray, y: list[int]) -> None: ...
    def predict(self, X: np.ndarray, threshold: float = 0.5) -> list[int]: ...
    def predict_proba(self, X: np.ndarray) -> list[float]: ...
    def score(self, X: np.ndarray, y: list[int]) -> float: ...
    def compute_loss(self, X: np.ndarray, y: list[int]) -> float: ...
    @property
    def weights(self) -> Vector: ...
    @property
    def bias(self) -> float: ...
    @property
    def learning_rate(self) -> float: ...
    @property
    def epochs(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

def accuracy(y_true: list[int], y_pred: list[int]) -> float: ...
def mse(y_true: list[float], y_pred: list[float]) -> float: ...
def r2_score(y_true: list[float], y_pred: list[float]) -> float: ...
def set_seed(seed: int) -> None: ...
def get_seed() -> int: ...

class TensorView:
    def __init__(self) -> None: ...
    def rows(self) -> int: ...
    def cols(self) -> int: ...
    def stride(self) -> int: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def to_matrix(self) -> Matrix: ...
    def __call__(self, r: int, c: int) -> float: ...
    def __getitem__(self, idx: tuple[int, int]) -> float: ...

def tensor_view_from_numpy(arr: np.ndarray) -> TensorView: ...

class IngestionCursor:
    epoch: int
    sample_offset: int
    checksum: int
    def __init__(self) -> None: ...
    def to_string(self) -> str: ...
    @staticmethod
    def from_string(s: str) -> IngestionCursor: ...

class IdempotentSampler:
    seed: int
    def __init__(self, seed: int = 42) -> None: ...
    def generate_indices(self, total_samples: int, epoch: int = 0) -> list[int]: ...

class MMapBuffer:
    def __init__(self, filepath: str) -> None: ...
    def rows(self) -> int: ...
    def cols(self) -> int: ...
    def size(self) -> int: ...
    def checksum(self) -> int: ...
    def filepath(self) -> str: ...
    def get_slice(self, start_row: int, num_rows: int) -> TensorView: ...
    def full_view(self) -> TensorView: ...
    @staticmethod
    def write_mldat(filepath: str, mat: Matrix) -> None: ...
    @staticmethod
    def write_mldat_numpy(filepath: str, arr: np.ndarray) -> None: ...
