from typing import List, Union
import numpy as np


class Vector:
    def __init__(self, data: Union[int, List[float]] = ...) -> None: ...
    def size(self) -> int: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, val: float) -> None: ...
    def dot(self, other: Vector) -> float: ...
    def norm(self) -> float: ...
    def normalized(self) -> Vector: ...
    def __add__(self, other: Vector) -> Vector: ...
    def __sub__(self, other: Vector) -> Vector: ...
    def __mul__(self, scalar: float) -> Vector: ...
    def __rmul__(self, scalar: float) -> Vector: ...
    def to_list(self) -> List[float]: ...


class Matrix:
    def __init__(self, rows: int = ..., cols: int = ...) -> None: ...
    def rows(self) -> int: ...
    def cols(self) -> int: ...
    def __call__(self, i: int, j: int) -> float: ...
    def __mul__(self, other: Matrix) -> Matrix: ...
    def transpose(self) -> Matrix: ...
    def identity(self, n: int) -> Matrix: ...
    def zeros(self, rows: int, cols: int) -> Matrix: ...
    def random(self, rows: int, cols: int) -> Matrix: ...
    def to_list(self) -> List[List[float]]: ...


class KNN:
    def __init__(self, k: int = 3) -> None: ...
    def fit(self, X: np.ndarray, y: List[int]) -> None: ...
    def predict(self, X: np.ndarray) -> List[int]: ...


def accuracy(y_true: List[int], y_pred: List[int]) -> float: ...
def mse(y_true: List[float], y_pred: List[float]) -> float: ...